### ISSUE TITLE
Add .rubocop.yml file to template

### ISSUE THREAD

**Issue by simpsonjt66** [simpsonjt66/dotfiles#7]
Add the .rubocop.yml file with sensible defaults for rails to the rails template.

**Comment by simpsonjt66** [comment]
```yml
require:
  - rubocop-rspec
  - rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Naming/PredicateName:
    Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/system/*.rb'
```
